name: proteus_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - rdkit
  - numpy
  - lammps
  - fastapi
  - uvicorn
  - python-multipart
  - celery
  - redis
  - sqlalchemy
  - alembic
  - matplotlib
  - pip
  - pip:
    - ovito
    - fastapi-mail
    - psycopg2-binary
    - reportlab